spring:
  cache:
    type: redis
  data:
    redis:
      host: ${redis_host:localhost}
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${db_host:localhost}:5432/products
    username: ${db_user}
    password: ${db_password}
    driverClassName: org.postgresql.Driver